### ISSUE TITLE
Check for "negative number of electrons"

### ISSUE THREAD

**Issue by xamberl** [xamberl/DFT-raMO#37]
https://github.com/xamberl/DFT-raMO/blob/93790c6ef440148718c020bcb81fb29bcd2f10d8/src/data.jl#L206

For now, the number of electrons left *can* be negative due to the Fermi energy in VASP being imprecise. I need to add a check or a warning at the beginning of the DFT-raMO analysis, which will suggest the user to adjust `emax`.

Additionally, users might want to artificially raise `emax` to see a raMO scheme at an increased electron count, which means the number of electrons left with respect to the calculated composition *will* be negative.

I think we should comment out this assertion for now.

**Comment by brainandforce** [comment]
Good point - VASP does have a number of weird numerical issues, and for raMO schemes with extra electron counts this would be a problem. An `@warn` or other message is suitable.

**Comment by brainandforce** [comment]
Should be resolved in #39.
