### ISSUE TITLE
Refactoring `OccupiedStates`

### ISSUE THREAD

**Issue by brainandforce** [xamberl/DFT-raMO#38]
I think `OccupiedStates` is ripe for a refactoring.

The first bit I noticed was that the `kpt` and `G` fields are matrices with the same element repeated along each column or row, respectively, and therefore they could likely be reduced to vectors so that we keep the storage space down.

Second, we can probably treat `OccupiedStates` like a matrix, and have it subtype `DenseMatrix{ComplexF32}`. Along with a `Base.getindex` definition, this would allow it to be have just like a regular `Matrix{ComplexF32}` and simplify a number of methods.

This would also involve changes to `get_occupied_states`, but I think a more elegant way to approach this is by defining a constructor for `OccupiedStates` that uses the new `raMOInput` or `raMODFTData` structs we've been working on.

**Comment by xamberl** [comment]
Yes, definitely `kpt` and `G` can be vectorized. That was an artifact from translating the code and testing out ways to access the necessary data.

`get_occupied_states` is in desperate need of refactorization, would be a good item to prioritize.
